Utils package (task 2)
ozoncp/ocp-survey-api pull request #2
Opened 2021-07-17 08:42 UTC by yuujiin

Implemented SplitSlice, FilterSlice, ReverseMap functions.

2021-07-18 21:52 UTC, dk13danger requested changes

2021-07-18 21:52 UTC, dk13danger commented on internal/utils/slice.go
> +	size := int(chunkSize)
Давай для `chunkSize` просто `int` тип (ты все равно в строчке 5 проверяешь на `<= 0`), чтобы тут не преобразовывать

2021-07-18 21:52 UTC, dk13danger commented on internal/utils/slice.go
> +func SplitSlice(s []int, chunkSize uint) [][]int {
Давай s назовем `slice`. Так понятнее

2021-07-18 21:52 UTC, dk13danger commented on internal/utils/slice.go
> +	os := make([][]int, count)
`os` я так и не понял что означает :-) s - это slice, я думаю) Мож, `outputSlice`? :-)
Обычно я называю то, что возвращается `res` (просто на заметку: делюсь своей практикой)

2021-07-18 21:52 UTC, dk13danger commented on internal/utils/slice.go
> +	os[i] = s[start:]	// last chunk
Немного сложно. Можно было в 3 строчки уместить:
```
for i := 0; i < len(s); i++ {
	os[i/chunkSize] = append(os[i/chunkSize], s[i])
}
```

2021-07-18 21:52 UTC, dk13danger commented on internal/utils/slice.go
> +	filter := [...]int{-1, 0, 1}	// hardcoded list
Во-первых, давай тут мапу. Чтобы сложность выборки была О(1)
Во-вторых, это должно прилетать сверху от потребителя функции
В-третьих, давай не использовать "goto" синтаксис

2021-07-19 11:32 UTC, yuujiin commented on internal/utils/slice.go
> +	os := make([][]int, count)
Да, имел в виду `outputSlice` :)
Но вариант с `res` нагляднее, исправил 👍

2021-07-19 11:35 UTC, yuujiin commented on internal/utils/slice.go
> +	filter := [...]int{-1, 0, 1}	// hardcoded list
Переделал с использованием `map`, вынес фильтр в параметры.

2021-07-19 11:41 UTC, yuujiin commented on internal/utils/slice.go
> +	os[i] = s[start:]	// last chunk
Мой вариант немного менее наглядный, но должен работать быстрее, т.к. мы просто нарезаем исходный слайс без использования `append` и без итерирования по всем элементам чанка. Предлагаю оставить как есть :)

Вот, написал бенчмарки:
```
len(slice) = 1000000
chunkSize  = 100
BenchmarkSplitSlice-8              16262             95147 ns/op          245761 B/op          1 allocs/op
BenchmarkSplitSliceSimple-8           85          12244916 ns/op        20645784 B/op      80001 allocs/op
```
```
len(slice) = 1000000
chunkSize  = 10000
BenchmarkSplitSlice-8            1574331              1631 ns/op            2688 B/op          1 allocs/op
BenchmarkSplitSliceSimple-8           74          14768886 ns/op        38632339 B/op       2001 allocs/op
```

2021-07-19 21:31 UTC, dk13danger commented on internal/utils/slice.go
> +	os[i] = s[start:]	// last chunk
Да, тут ты прав

2021-07-19 21:31 UTC, dk13danger approved these changes

2021-07-19 21:31 UTC, merged