Flusher & Repo (task 4)
ozoncp/ocp-survey-api pull request #4
Opened 2021-07-29 13:54 UTC by yuujiin

Задание IV.

- Добавлены интерфейсы `Flusher` и `Repo`.
- Имплементация `flusher` с поддержкой батчевого сохранения.
- Генерация моков с использованием `mockgen`.
- Тесты `flusher` с применением `ginkgo` и `gomega`.

2021-08-02 13:20 UTC, dk13danger requested changes

2021-08-02 13:20 UTC, dk13danger commented on internal/flusher/flusher.go
> +	Flush(surveys []models.Survey) ([]models.Survey, error)
По заданию другой интерфейс: без error

2021-08-02 13:20 UTC, dk13danger commented on internal/flusher/flusher.go
> +func New(chunkSize int, surveyRepo repo.Repo) (Flusher, error) {
Тут тоже. Без error

2021-08-02 13:20 UTC, dk13danger commented on internal/flusher/flusher.go
> +			return surveys[f.chunkSize*chunkIdx:], fmt.Errorf("flush error: %w", err)
Как я выше писал, ошибку мы не возвращаем. Мы должны вернуть только то, что смогли сохранить в сторадж

2021-08-02 13:20 UTC, dk13danger commented on internal/mockgen.go
> +//go:generate mockgen -destination=./mocks/flusher_mock.go -package=mocks github.com/ozoncp/ocp-survey-api/internal/flusher Flusher
Моки нужны по заданию только для Repo же

2021-08-02 13:20 UTC, dk13danger commented on internal/utils/slice.go
> +	if len(slice) == 0 || chunkSize <= 0 {
.

2021-08-02 13:20 UTC, dk13danger commented on internal/utils/survey.go
> +		return nil, nil
Я бы оставил тут ошибку

2021-08-02 15:13 UTC, yuujiin commented on internal/flusher/flusher.go
> +			return surveys[f.chunkSize*chunkIdx:], fmt.Errorf("flush error: %w", err)
В задании явно не указано, но мне показалось логичным возвращать слайс элементов, которые **не удалось** сохранить. Таким образом, можно просто использовать этот слайс для следующих попыток (до тех пор, пока в нем не останется элементов). 
Возврат ошибки убрал.

2021-08-02 15:13 UTC, yuujiin commented on internal/mockgen.go
> +//go:generate mockgen -destination=./mocks/flusher_mock.go -package=mocks github.com/ozoncp/ocp-survey-api/internal/flusher Flusher
Точно, убрал лишнее

2021-08-02 15:14 UTC, yuujiin commented on internal/utils/survey.go
> +		return nil, nil
+

2021-08-02 15:14 UTC, yuujiin commented on internal/flusher/flusher.go
> +func New(chunkSize int, surveyRepo repo.Repo) (Flusher, error) {
++

2021-08-02 15:15 UTC, yuujiin commented on internal/flusher/flusher.go
> +	Flush(surveys []models.Survey) ([]models.Survey, error)
++

2021-08-03 21:22 UTC, dk13danger approved these changes

2021-08-03 21:22 UTC, merged